package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyAttachmentType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyAttachmentTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyAttachmentType self()
    {
        return (MyAttachmentType)this;
    }

    //##################################################
    //# extensions
    //##################################################

}
