package com.app.model;

import com.kodemore.utility.KmEnumIF;
import com.kodemore.utility.Kmu;

import com.app.dao.base.MyDaoAccess;
import com.app.model.base.MyAttachmentOwnerType;
import com.app.utility.MyGlobals;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyAttachmentOwnerTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyAttachmentOwnerType self()
    {
        return (MyAttachmentOwnerType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    default MyAttachmentOwnerIF findOwner(String uid)
    {
        MyDaoAccess access = MyGlobals.getAccess();

        MyAttachmentOwnerType type = self();
        switch ( type )
        {
            case Project:
                return access.findProjectUid(uid);

            case Customer:
                return access.findCustomerUid(uid);

            case Site:
                return access.findSiteUid(uid);
        }
        throw Kmu.newEnumError(type);
    }
}
