package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyAuditBundleChangeType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyAuditBundleChangeTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyAuditBundleChangeType self()
    {
        return (MyAuditBundleChangeType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
