package com.app.model;

import com.kodemore.utility.KmEnumIF;
import com.kodemore.utility.Kmu;

import com.app.dao.base.MyDaoAccess;
import com.app.macro.MyMacroContextType;
import com.app.model.base.MyBlurbOwnerType;
import com.app.utility.MyGlobals;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyBlurbOwnerTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyBlurbOwnerType self()
    {
        return (MyBlurbOwnerType)this;
    }

    //##################################################
    //# owner
    //##################################################

    default MyBlurbOwnerIF findOwnerUid(String uid)
    {
        MyDaoAccess access = MyGlobals.getAccess();

        MyBlurbOwnerType type = self();
        switch ( type )
        {
            case Project:
                return access.findProjectUid(uid);

            case Site:
                return access.findSiteUid(uid);
        }
        throw Kmu.newEnumError(type);
    }

    //##################################################
    //# extensions
    //##################################################

    default MyMacroContextType toMacroContextType()
    {
        switch ( self() )
        {
            case Project:
                return MyMacroContextType.Project;

            case Site:
                return MyMacroContextType.Site;
        }
        throw Kmu.newEnumError(this);
    }

}
