package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyChoiceType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyChoiceTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyChoiceType self()
    {
        return (MyChoiceType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
