package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyDefaultRecipientType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyDefaultRecipientTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyDefaultRecipientType self()
    {
        return (MyDefaultRecipientType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
