package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyDownloadType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyDownloadTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyDownloadType self()
    {
        return (MyDownloadType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
