package com.app.model;

import com.kodemore.utility.KmEnumIF;
import com.kodemore.utility.Kmu;

import com.app.dao.base.MyDaoAccess;
import com.app.macro.MyMacroContextType;
import com.app.model.base.MyEmailTemplateContextType;
import com.app.utility.MyGlobals;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyEmailTemplateContextTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyEmailTemplateContextType self()
    {
        return (MyEmailTemplateContextType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    default MyEmailTemplateContextIF findContextUid(String uid)
    {
        MyDaoAccess access = MyGlobals.getAccess();

        MyEmailTemplateContextType type = self();
        switch ( type )
        {
            case Project:
                return access.findProjectUid(uid);

            case Site:
                return access.findSiteUid(uid);
        }
        throw Kmu.newEnumError(type);
    }

    default MyMacroContextType toMacroContextType()
    {
        MyEmailTemplateContextType type = self();
        switch ( type )
        {
            case Project:
                return MyMacroContextType.Project;

            case Site:
                return MyMacroContextType.Site;
        }
        throw Kmu.newEnumError(type);
    }
}
