package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyEmailRecipientType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyEmailRecipientTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyEmailRecipientType self()
    {
        return (MyEmailRecipientType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
