package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyEmailPartType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyEmailPartTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyEmailPartType self()
    {
        return (MyEmailPartType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
