package com.app.model;

import com.kodemore.utility.KmEnumIF;
import com.kodemore.utility.Kmu;

import com.app.model.base.MyFeedbackStatus;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyFeedbackStatusIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyFeedbackStatus self()
    {
        return (MyFeedbackStatus)this;
    }

    //##################################################
    //# extensions
    //##################################################

    default boolean isOpen()
    {
        switch ( self() )
        {
            case Pending:
                return true;

            case Dropped:
            case Resolved:
                return false;
        }
        throw Kmu.newEnumError(this);
    }
}
