package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyFeedbackType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyFeedbackTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyFeedbackType self()
    {
        return (MyFeedbackType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
