package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyFilterTemplateType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyFilterTemplateTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyFilterTemplateType self()
    {
        return (MyFilterTemplateType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
