package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyMemberRole;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyMemberRoleIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyMemberRole self()
    {
        return (MyMemberRole)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
