package com.app.model;

import com.kodemore.utility.KmEnumIF;
import com.kodemore.utility.Kmu;

import com.app.dao.base.MyDaoAccess;
import com.app.model.base.MyNoteOwnerType;
import com.app.utility.MyGlobals;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyNoteOwnerTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyNoteOwnerType self()
    {
        return (MyNoteOwnerType)this;
    }

    //##################################################
    //# owner
    //##################################################

    default MyNoteOwnerIF findOwnerUid(String uid)
    {
        MyDaoAccess access = MyGlobals.getAccess();

        MyNoteOwnerType type = self();
        switch ( type )
        {
            case Project:
                return access.findProjectUid(uid);

            case Customer:
                return access.findCustomerUid(uid);

            case Site:
                return access.findSiteUid(uid);
        }
        throw Kmu.newEnumError(type);
    }
}
