package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyNoteSourceType;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyNoteSourceTypeIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyNoteSourceType self()
    {
        return (MyNoteSourceType)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
