package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyPriorityCategory;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyPriorityCategoryIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyPriorityCategory self()
    {
        return (MyPriorityCategory)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
