package com.app.model;

import com.kodemore.utility.KmEnumIF;

import com.app.model.base.MyUserRole;

/**
 * I provide ad hoc custom extensions to the autogenerated enum.
 */
public interface MyUserRoleIF
    extends KmEnumIF
{
    //##################################################
    //# self
    //##################################################

    default MyUserRole self()
    {
        return (MyUserRole)this;
    }

    //##################################################
    //# extensions
    //##################################################

    // put custom methods here
}
