//###############################################################
//###############################################################
//##
//##  AUTO GENERATED - DO NOT EDIT
//##
//###############################################################
//###############################################################

package com.app.ui.servlet.base;

import com.kodemore.servlet.*;

import com.app.ui.page.general.*;
import com.app.ui.page.login.*;
import com.app.ui.page.manageAttentionGroups.*;
import com.app.ui.page.manageCategories.*;
import com.app.ui.page.manageDepots.*;
import com.app.ui.page.manageMembers.*;
import com.app.ui.page.managePowerTypes.*;
import com.app.ui.page.manageProducts.*;
import com.app.ui.page.manageProjects.*;
import com.app.ui.page.manageRegions.*;
import com.app.ui.page.manageShipCarriers.*;
import com.app.ui.page.manageSkills.*;
import com.app.ui.page.manageUsers.*;
import com.app.ui.page.manageVendors.*;
import com.app.ui.page.manageVisitTypes.*;
import com.app.ui.page.test.*;
import com.app.ui.page.tools.*;
import com.app.ui.page.userProfile.*;

public abstract class MyPageRegistryBase
    extends ScPageRegistry
{
    @Override
    protected void registerPages()
    {
        super.registerPages();

        MyAbsoluteLayoutTestPage.installInstance();
        MyAccordionTestPage.installInstance();
        MyAnimationTestPage.installInstance();
        MyAutoCompleteTestPage.installInstance();
        MyBarcodeTestPage.installInstance();
        MyBlankTestPage.installInstance();
        MyBlockTestPage.installInstance();
        MyBorderLayoutTestPage.installInstance();
        MyBorderTestPage.installInstance();
        MyCardFlipTestPage.installInstance();
        MyColorFieldTestPage.installInstance();
        MyDashboardPage.installInstance();
        MyDateFieldTestPage.installInstance();
        MyDevApplicationLogsPage.installInstance();
        MyDevApplicationPropertiesPage.installInstance();
        MyDevBeanShellPage.installInstance();
        MyDevEmailsPage.installInstance();
        MyDevEnvironmentVariablesPage.installInstance();
        MyDevHibernateCachePage.installInstance();
        MyDevPerformanceLogPage.installInstance();
        MyDevSharedFileBrowserPage.installInstance();
        MyDevSqlPage.installInstance();
        MyDevSystemPropertiesPage.installInstance();
        MyDevUsersPage.installInstance();
        MyDevUtilityPage.installInstance();
        MyDialogTestPage.installInstance();
        MyDomainDropdownSetValueTestPage.installInstance();
        MyDownloadTestPage.installInstance();
        MyDragTestPage.installInstance();
        MyDraggableMultiSelectTestPage.installInstance();
        MyDropzoneTestPage.installInstance();
        MyEqualizeTestPage.installInstance();
        MyFacebookTestPage.installInstance();
        MyFieldTestPage.installInstance();
        MyFilterTableRowTestPage.installInstance();
        MyFlexboxTestPage.installInstance();
        MyFormTestPage.installInstance();
        MyGmailTestPage.installInstance();
        MyGoogleChartTestPage.installInstance();
        MyGradientTestPage.installInstance();
        MyGridTestPage.installInstance();
        MyGroupIconHeaderTestPage.installInstance();
        MyGroupTestPage.installInstance();
        MyHideErrorsTestPage.installInstance();
        MyHoverTestPage.installInstance();
        MyLocalValueTestPage.installInstance();
        MyManageAttentionGroupsPage.installInstance();
        MyManageCategoriesPage.installInstance();
        MyManageDepotsPage.installInstance();
        MyManageMembersPage.installInstance();
        MyManagePowerTypesPage.installInstance();
        MyManageProductsPage.installInstance();
        MyManageProjectsPage.installInstance();
        MyManageRegionsPage.installInstance();
        MyManageShipCarriersPage.installInstance();
        MyManageSkillsPage.installInstance();
        MyManageUsersPage.installInstance();
        MyManageVendorsPage.installInstance();
        MyManageVisitTypesPage.installInstance();
        MyMemoryLeakTestPage.installInstance();
        MyNavigationTest1Page.installInstance();
        MyNavigationTest2Page.installInstance();
        MyNotebookTestPage.installInstance();
        MyNvd3ChartTestPage.installInstance();
        MyOpenWindowTestPage.installInstance();
        MyOrdersPage.installInstance();
        MyPaddingTestPage.installInstance();
        MyPasswordResetPage.installInstance();
        MyPlaceholderTestPage.installInstance();
        MyRadioButtonTestPage.installInstance();
        MyReportsPage.installInstance();
        MyScriptTestPage.installInstance();
        MySharedStateTest1Page.installInstance();
        MySharedStateTest2Page.installInstance();
        MySignInPage.installInstance();
        MySignOutPage.installInstance();
        MySlowTestPage.installInstance();
        MySmtpTestPage.installInstance();
        MySplitterTestPage.installInstance();
        MyStaticIncludeTestPage.installInstance();
        MyTabbedTestPage.installInstance();
        MyTasksPage.installInstance();
        MyTimeAgoTestPage.installInstance();
        MyTimeoutPage.installInstance();
        MyTitlePanelTestPage.installInstance();
        MyToastTestPage.installInstance();
        MyUserActivationPage.installInstance();
        MyUserProfilePage.installInstance();
        MyWyattTestPage.installInstance();

        add(MyAbsoluteLayoutTestPage.getInstance());
        add(MyAccordionTestPage.getInstance());
        add(MyAnimationTestPage.getInstance());
        add(MyAutoCompleteTestPage.getInstance());
        add(MyBarcodeTestPage.getInstance());
        add(MyBlankTestPage.getInstance());
        add(MyBlockTestPage.getInstance());
        add(MyBorderLayoutTestPage.getInstance());
        add(MyBorderTestPage.getInstance());
        add(MyCardFlipTestPage.getInstance());
        add(MyColorFieldTestPage.getInstance());
        add(MyDashboardPage.getInstance());
        add(MyDateFieldTestPage.getInstance());
        add(MyDevApplicationLogsPage.getInstance());
        add(MyDevApplicationPropertiesPage.getInstance());
        add(MyDevBeanShellPage.getInstance());
        add(MyDevEmailsPage.getInstance());
        add(MyDevEnvironmentVariablesPage.getInstance());
        add(MyDevHibernateCachePage.getInstance());
        add(MyDevPerformanceLogPage.getInstance());
        add(MyDevSharedFileBrowserPage.getInstance());
        add(MyDevSqlPage.getInstance());
        add(MyDevSystemPropertiesPage.getInstance());
        add(MyDevUsersPage.getInstance());
        add(MyDevUtilityPage.getInstance());
        add(MyDialogTestPage.getInstance());
        add(MyDomainDropdownSetValueTestPage.getInstance());
        add(MyDownloadTestPage.getInstance());
        add(MyDragTestPage.getInstance());
        add(MyDraggableMultiSelectTestPage.getInstance());
        add(MyDropzoneTestPage.getInstance());
        add(MyEqualizeTestPage.getInstance());
        add(MyFacebookTestPage.getInstance());
        add(MyFieldTestPage.getInstance());
        add(MyFilterTableRowTestPage.getInstance());
        add(MyFlexboxTestPage.getInstance());
        add(MyFormTestPage.getInstance());
        add(MyGmailTestPage.getInstance());
        add(MyGoogleChartTestPage.getInstance());
        add(MyGradientTestPage.getInstance());
        add(MyGridTestPage.getInstance());
        add(MyGroupIconHeaderTestPage.getInstance());
        add(MyGroupTestPage.getInstance());
        add(MyHideErrorsTestPage.getInstance());
        add(MyHoverTestPage.getInstance());
        add(MyLocalValueTestPage.getInstance());
        add(MyManageAttentionGroupsPage.getInstance());
        add(MyManageCategoriesPage.getInstance());
        add(MyManageDepotsPage.getInstance());
        add(MyManageMembersPage.getInstance());
        add(MyManagePowerTypesPage.getInstance());
        add(MyManageProductsPage.getInstance());
        add(MyManageProjectsPage.getInstance());
        add(MyManageRegionsPage.getInstance());
        add(MyManageShipCarriersPage.getInstance());
        add(MyManageSkillsPage.getInstance());
        add(MyManageUsersPage.getInstance());
        add(MyManageVendorsPage.getInstance());
        add(MyManageVisitTypesPage.getInstance());
        add(MyMemoryLeakTestPage.getInstance());
        add(MyNavigationTest1Page.getInstance());
        add(MyNavigationTest2Page.getInstance());
        add(MyNotebookTestPage.getInstance());
        add(MyNvd3ChartTestPage.getInstance());
        add(MyOpenWindowTestPage.getInstance());
        add(MyOrdersPage.getInstance());
        add(MyPaddingTestPage.getInstance());
        add(MyPasswordResetPage.getInstance());
        add(MyPlaceholderTestPage.getInstance());
        add(MyRadioButtonTestPage.getInstance());
        add(MyReportsPage.getInstance());
        add(MyScriptTestPage.getInstance());
        add(MySharedStateTest1Page.getInstance());
        add(MySharedStateTest2Page.getInstance());
        add(MySignInPage.getInstance());
        add(MySignOutPage.getInstance());
        add(MySlowTestPage.getInstance());
        add(MySmtpTestPage.getInstance());
        add(MySplitterTestPage.getInstance());
        add(MyStaticIncludeTestPage.getInstance());
        add(MyTabbedTestPage.getInstance());
        add(MyTasksPage.getInstance());
        add(MyTimeAgoTestPage.getInstance());
        add(MyTimeoutPage.getInstance());
        add(MyTitlePanelTestPage.getInstance());
        add(MyToastTestPage.getInstance());
        add(MyUserActivationPage.getInstance());
        add(MyUserProfilePage.getInstance());
        add(MyWyattTestPage.getInstance());
    }
}
