//###############################################################
//###############################################################
//##
//##  AUTO GENERATED - DO NOT EDIT
//##
//###############################################################
//###############################################################

package com.app.ui.servlet.base;

import com.kodemore.servlet.ScPageRegistry;

import com.app.ui.page.general.MyDashboardPage;
import com.app.ui.page.general.MyOrdersPage;
import com.app.ui.page.general.MyReportsPage;
import com.app.ui.page.general.MySignOutPage;
import com.app.ui.page.general.MyTimeoutPage;
import com.app.ui.page.login.MyPasswordResetPage;
import com.app.ui.page.login.MySignInPage;
import com.app.ui.page.login.MyUserActivationPage;
import com.app.ui.page.manageDepots.MyManageDepotsPage;
import com.app.ui.page.manageMembers.MyManageMembersPage;
import com.app.ui.page.manageProjects.MyManageProjectsPage;
import com.app.ui.page.manageRegions.MyManageRegionsPage;
import com.app.ui.page.manageSkills.MyManageSkillsPage;
import com.app.ui.page.manageUsers.MyManageUsersPage;
import com.app.ui.page.manageVendors.MyManageVendorsPage;
import com.app.ui.page.test.MyAbsoluteLayoutTestPage;
import com.app.ui.page.test.MyAccordionTestPage;
import com.app.ui.page.test.MyAnimationTestPage;
import com.app.ui.page.test.MyAutoCompleteTestPage;
import com.app.ui.page.test.MyBarcodeTestPage;
import com.app.ui.page.test.MyBlankTestPage;
import com.app.ui.page.test.MyBlockTestPage;
import com.app.ui.page.test.MyBorderLayoutTestPage;
import com.app.ui.page.test.MyBorderTestPage;
import com.app.ui.page.test.MyCalendarTestPage;
import com.app.ui.page.test.MyCardFlipTestPage;
import com.app.ui.page.test.MyChoiceFieldTestPage;
import com.app.ui.page.test.MyColorFieldTestPage;
import com.app.ui.page.test.MyDateFieldTestPage;
import com.app.ui.page.test.MyDialogTestPage;
import com.app.ui.page.test.MyDomainDropdownSetValueTestPage;
import com.app.ui.page.test.MyDownloadTestPage;
import com.app.ui.page.test.MyDragTestPage;
import com.app.ui.page.test.MyDraggableMultiSelectTestPage;
import com.app.ui.page.test.MyDropzoneTestPage;
import com.app.ui.page.test.MyEqualizeTestPage;
import com.app.ui.page.test.MyFacebookTestPage;
import com.app.ui.page.test.MyFieldTestPage;
import com.app.ui.page.test.MyFieldsetTestPage;
import com.app.ui.page.test.MyFilterTableRowTestPage;
import com.app.ui.page.test.MyFlexboxTestPage;
import com.app.ui.page.test.MyFormTestPage;
import com.app.ui.page.test.MyGmailTestPage;
import com.app.ui.page.test.MyGoogleChartTestPage;
import com.app.ui.page.test.MyGradientTestPage;
import com.app.ui.page.test.MyGridTestPage;
import com.app.ui.page.test.MyGroupIconHeaderTestPage;
import com.app.ui.page.test.MyGroupTestPage;
import com.app.ui.page.test.MyHideErrorsTestPage;
import com.app.ui.page.test.MyHoverTestPage;
import com.app.ui.page.test.MyLocalValueTestPage;
import com.app.ui.page.test.MyMemoryLeakTestPage;
import com.app.ui.page.test.MyNavigationTest1Page;
import com.app.ui.page.test.MyNavigationTest2Page;
import com.app.ui.page.test.MyNotebookTestPage;
import com.app.ui.page.test.MyNvd3ChartTestPage;
import com.app.ui.page.test.MyOpenWindowTestPage;
import com.app.ui.page.test.MyPaddingTestPage;
import com.app.ui.page.test.MyPlaceholderTestPage;
import com.app.ui.page.test.MyRadioButtonTestPage;
import com.app.ui.page.test.MyRichTextEditorTestPage;
import com.app.ui.page.test.MyScriptTestPage;
import com.app.ui.page.test.MySharedStateTest1Page;
import com.app.ui.page.test.MySharedStateTest2Page;
import com.app.ui.page.test.MySlowTestPage;
import com.app.ui.page.test.MySmtpTestPage;
import com.app.ui.page.test.MySplitterTestPage;
import com.app.ui.page.test.MyStaticIncludeTestPage;
import com.app.ui.page.test.MyTabbedTestPage;
import com.app.ui.page.test.MyTimeAgoTestPage;
import com.app.ui.page.test.MyTitlePanelTestPage;
import com.app.ui.page.test.MyToastTestPage;
import com.app.ui.page.test.MyWyattTestPage;
import com.app.ui.page.tools.MyDevApplicationLogsPage;
import com.app.ui.page.tools.MyDevApplicationPropertiesPage;
import com.app.ui.page.tools.MyDevBeanShellPage;
import com.app.ui.page.tools.MyDevEmailsPage;
import com.app.ui.page.tools.MyDevEnvironmentVariablesPage;
import com.app.ui.page.tools.MyDevPerformanceLogDetailPage;
import com.app.ui.page.tools.MyDevPerformanceLogSummaryPage;
import com.app.ui.page.tools.MyDevSampleDataPage;
import com.app.ui.page.tools.MyDevSharedFileBrowserPage;
import com.app.ui.page.tools.MyDevSqlPage;
import com.app.ui.page.tools.MyDevSystemPropertiesPage;
import com.app.ui.page.tools.MyDevUsersPage;
import com.app.ui.page.tools.MyDevUtilityPage;
import com.app.ui.page.tools.MyHibernateCacheTestPage;
import com.app.ui.page.userProfile.MyUserProfilePage;

public abstract class MyPageRegistryBase
    extends ScPageRegistry
{
    @Override
    protected void registerPages()
    {
        super.registerPages();

        MyAbsoluteLayoutTestPage.installInstance();
        MyAccordionTestPage.installInstance();
        MyAnimationTestPage.installInstance();
        MyAutoCompleteTestPage.installInstance();
        MyBarcodeTestPage.installInstance();
        MyBlankTestPage.installInstance();
        MyBlockTestPage.installInstance();
        MyBorderLayoutTestPage.installInstance();
        MyBorderTestPage.installInstance();
        MyCalendarTestPage.installInstance();
        MyCardFlipTestPage.installInstance();
        MyChoiceFieldTestPage.installInstance();
        MyColorFieldTestPage.installInstance();
        MyDashboardPage.installInstance();
        MyDateFieldTestPage.installInstance();
        MyDevApplicationLogsPage.installInstance();
        MyDevApplicationPropertiesPage.installInstance();
        MyDevBeanShellPage.installInstance();
        MyDevEmailsPage.installInstance();
        MyDevEnvironmentVariablesPage.installInstance();
        MyDevPerformanceLogDetailPage.installInstance();
        MyDevPerformanceLogSummaryPage.installInstance();
        MyDevSampleDataPage.installInstance();
        MyDevSharedFileBrowserPage.installInstance();
        MyDevSqlPage.installInstance();
        MyDevSystemPropertiesPage.installInstance();
        MyDevUsersPage.installInstance();
        MyDevUtilityPage.installInstance();
        MyDialogTestPage.installInstance();
        MyDomainDropdownSetValueTestPage.installInstance();
        MyDownloadTestPage.installInstance();
        MyDragTestPage.installInstance();
        MyDraggableMultiSelectTestPage.installInstance();
        MyDropzoneTestPage.installInstance();
        MyEqualizeTestPage.installInstance();
        MyFacebookTestPage.installInstance();
        MyFieldTestPage.installInstance();
        MyFieldsetTestPage.installInstance();
        MyFilterTableRowTestPage.installInstance();
        MyFlexboxTestPage.installInstance();
        MyFormTestPage.installInstance();
        MyGmailTestPage.installInstance();
        MyGoogleChartTestPage.installInstance();
        MyGradientTestPage.installInstance();
        MyGridTestPage.installInstance();
        MyGroupIconHeaderTestPage.installInstance();
        MyGroupTestPage.installInstance();
        MyHibernateCacheTestPage.installInstance();
        MyHideErrorsTestPage.installInstance();
        MyHoverTestPage.installInstance();
        MyLocalValueTestPage.installInstance();
        MyManageDepotsPage.installInstance();
        MyManageMembersPage.installInstance();
        MyManageProjectsPage.installInstance();
        MyManageRegionsPage.installInstance();
        MyManageSkillsPage.installInstance();
        MyManageUsersPage.installInstance();
        MyManageVendorsPage.installInstance();
        MyMemoryLeakTestPage.installInstance();
        MyNavigationTest1Page.installInstance();
        MyNavigationTest2Page.installInstance();
        MyNotebookTestPage.installInstance();
        MyNvd3ChartTestPage.installInstance();
        MyOpenWindowTestPage.installInstance();
        MyOrdersPage.installInstance();
        MyPaddingTestPage.installInstance();
        MyPasswordResetPage.installInstance();
        MyPlaceholderTestPage.installInstance();
        MyRadioButtonTestPage.installInstance();
        MyReportsPage.installInstance();
        MyRichTextEditorTestPage.installInstance();
        MyScriptTestPage.installInstance();
        MySharedStateTest1Page.installInstance();
        MySharedStateTest2Page.installInstance();
        MySignInPage.installInstance();
        MySignOutPage.installInstance();
        MySlowTestPage.installInstance();
        MySmtpTestPage.installInstance();
        MySplitterTestPage.installInstance();
        MyStaticIncludeTestPage.installInstance();
        MyTabbedTestPage.installInstance();
        MyTimeAgoTestPage.installInstance();
        MyTimeoutPage.installInstance();
        MyTitlePanelTestPage.installInstance();
        MyToastTestPage.installInstance();
        MyUserActivationPage.installInstance();
        MyUserProfilePage.installInstance();
        MyWyattTestPage.installInstance();

        add(MyAbsoluteLayoutTestPage.getInstance());
        add(MyAccordionTestPage.getInstance());
        add(MyAnimationTestPage.getInstance());
        add(MyAutoCompleteTestPage.getInstance());
        add(MyBarcodeTestPage.getInstance());
        add(MyBlankTestPage.getInstance());
        add(MyBlockTestPage.getInstance());
        add(MyBorderLayoutTestPage.getInstance());
        add(MyBorderTestPage.getInstance());
        add(MyCalendarTestPage.getInstance());
        add(MyCardFlipTestPage.getInstance());
        add(MyChoiceFieldTestPage.getInstance());
        add(MyColorFieldTestPage.getInstance());
        add(MyDashboardPage.getInstance());
        add(MyDateFieldTestPage.getInstance());
        add(MyDevApplicationLogsPage.getInstance());
        add(MyDevApplicationPropertiesPage.getInstance());
        add(MyDevBeanShellPage.getInstance());
        add(MyDevEmailsPage.getInstance());
        add(MyDevEnvironmentVariablesPage.getInstance());
        add(MyDevPerformanceLogDetailPage.getInstance());
        add(MyDevPerformanceLogSummaryPage.getInstance());
        add(MyDevSampleDataPage.getInstance());
        add(MyDevSharedFileBrowserPage.getInstance());
        add(MyDevSqlPage.getInstance());
        add(MyDevSystemPropertiesPage.getInstance());
        add(MyDevUsersPage.getInstance());
        add(MyDevUtilityPage.getInstance());
        add(MyDialogTestPage.getInstance());
        add(MyDomainDropdownSetValueTestPage.getInstance());
        add(MyDownloadTestPage.getInstance());
        add(MyDragTestPage.getInstance());
        add(MyDraggableMultiSelectTestPage.getInstance());
        add(MyDropzoneTestPage.getInstance());
        add(MyEqualizeTestPage.getInstance());
        add(MyFacebookTestPage.getInstance());
        add(MyFieldTestPage.getInstance());
        add(MyFieldsetTestPage.getInstance());
        add(MyFilterTableRowTestPage.getInstance());
        add(MyFlexboxTestPage.getInstance());
        add(MyFormTestPage.getInstance());
        add(MyGmailTestPage.getInstance());
        add(MyGoogleChartTestPage.getInstance());
        add(MyGradientTestPage.getInstance());
        add(MyGridTestPage.getInstance());
        add(MyGroupIconHeaderTestPage.getInstance());
        add(MyGroupTestPage.getInstance());
        add(MyHibernateCacheTestPage.getInstance());
        add(MyHideErrorsTestPage.getInstance());
        add(MyHoverTestPage.getInstance());
        add(MyLocalValueTestPage.getInstance());
        add(MyManageDepotsPage.getInstance());
        add(MyManageMembersPage.getInstance());
        add(MyManageProjectsPage.getInstance());
        add(MyManageRegionsPage.getInstance());
        add(MyManageSkillsPage.getInstance());
        add(MyManageUsersPage.getInstance());
        add(MyManageVendorsPage.getInstance());
        add(MyMemoryLeakTestPage.getInstance());
        add(MyNavigationTest1Page.getInstance());
        add(MyNavigationTest2Page.getInstance());
        add(MyNotebookTestPage.getInstance());
        add(MyNvd3ChartTestPage.getInstance());
        add(MyOpenWindowTestPage.getInstance());
        add(MyOrdersPage.getInstance());
        add(MyPaddingTestPage.getInstance());
        add(MyPasswordResetPage.getInstance());
        add(MyPlaceholderTestPage.getInstance());
        add(MyRadioButtonTestPage.getInstance());
        add(MyReportsPage.getInstance());
        add(MyRichTextEditorTestPage.getInstance());
        add(MyScriptTestPage.getInstance());
        add(MySharedStateTest1Page.getInstance());
        add(MySharedStateTest2Page.getInstance());
        add(MySignInPage.getInstance());
        add(MySignOutPage.getInstance());
        add(MySlowTestPage.getInstance());
        add(MySmtpTestPage.getInstance());
        add(MySplitterTestPage.getInstance());
        add(MyStaticIncludeTestPage.getInstance());
        add(MyTabbedTestPage.getInstance());
        add(MyTimeAgoTestPage.getInstance());
        add(MyTimeoutPage.getInstance());
        add(MyTitlePanelTestPage.getInstance());
        add(MyToastTestPage.getInstance());
        add(MyUserActivationPage.getInstance());
        add(MyUserProfilePage.getInstance());
        add(MyWyattTestPage.getInstance());
    }
}
