//###############################################################
//###############################################################
//##
//##  AUTO GENERATED - DO NOT EDIT
//##
//###############################################################
//###############################################################

package com.app.ui.servlet.base;

import com.kodemore.servlet.*;

import com.app.ui.dashboard.core.*;
import com.app.ui.page.*;
import com.app.ui.page.general.*;
import com.app.ui.page.login.*;
import com.app.ui.page.manage.project.*;
import com.app.ui.page.manage.tenant.*;
import com.app.ui.page.manage.user.*;
import com.app.ui.page.report.*;
import com.app.ui.page.test.*;
import com.app.ui.page.tools.*;

public abstract class MyPageRegistryBase
    extends ScPageRegistry
{
    @Override
    protected void registerPages()
    {
        super.registerPages();

        MyAbsoluteLayoutTestPage.installInstance();
        MyAccordionTestPage.installInstance();
        MyAddressFieldTestPage.installInstance();
        MyAdminMenuPage.installInstance();
        MyAjaxCalendarTestPage.installInstance();
        MyAnimationTestPage.installInstance();
        MyAuditLogReportPage.installInstance();
        MyAutoCompleteTestPage.installInstance();
        MyBarcodeFieldTestPage.installInstance();
        MyBarcodeTestPage.installInstance();
        MyBlankTestPage.installInstance();
        MyBlockTestPage.installInstance();
        MyBorderLayoutTestPage.installInstance();
        MyBorderTestPage.installInstance();
        MyCardFlipTestPage.installInstance();
        MyCheckboxListTestPage.installInstance();
        MyChoiceFieldTestPage.installInstance();
        MyColorFieldTestPage.installInstance();
        MyCookieTestPage.installInstance();
        MyDashboardPage.installInstance();
        MyDateFieldTestPage.installInstance();
        MyDateIntervalFieldTestPage.installInstance();
        MyDetachedGroupTestPage.installInstance();
        MyDevApplicationLogsPage.installInstance();
        MyDevApplicationPropertiesPage.installInstance();
        MyDevBeanShellPage.installInstance();
        MyDevDataFixPage.installInstance();
        MyDevEmailsPage.installInstance();
        MyDevEnvironmentVariablesPage.installInstance();
        MyDevPerformanceLogDetailPage.installInstance();
        MyDevPerformanceLogSummaryPage.installInstance();
        MyDevSharedFileBrowserPage.installInstance();
        MyDevSqlPage.installInstance();
        MyDevSystemPropertiesPage.installInstance();
        MyDevUsersPage.installInstance();
        MyDevUtilityPage.installInstance();
        MyDialogTestPage.installInstance();
        MyDomainDropdownTestPage.installInstance();
        MyDownloadTestPage.installInstance();
        MyDragTestPage.installInstance();
        MyDropdownFieldTestPage.installInstance();
        MyDropzoneTestPage.installInstance();
        MyFacebookTestPage.installInstance();
        MyFieldTestPage.installInstance();
        MyFieldsetTestPage.installInstance();
        MyFilterTableRowTestPage.installInstance();
        MyFlexboxTestPage.installInstance();
        MyFormTestPage.installInstance();
        MyGmailTestPage.installInstance();
        MyGradientTestPage.installInstance();
        MyGridTestPage.installInstance();
        MyGroupTestPage.installInstance();
        MyHibernateCacheTestPage.installInstance();
        MyHiddenFieldTestPage.installInstance();
        MyHideErrorsTestPage.installInstance();
        MyHoverTestPage.installInstance();
        MyIntacctTestPage.installInstance();
        MyListCalendarTestPage.installInstance();
        MyListFieldTestPage.installInstance();
        MyLocalValueTestPage.installInstance();
        MyLoginPage.installInstance();
        MyLogoutPage.installInstance();
        MyMemoryLeakTestPage.installInstance();
        MyMultiTupleViewTestPage.installInstance();
        MyNavigation1TestPage.installInstance();
        MyNavigation2TestPage.installInstance();
        MyNotebookTestPage.installInstance();
        MyNvd3ChartTestPage.installInstance();
        MyOldValuesTestPage.installInstance();
        MyOpenWindowTestPage.installInstance();
        MyPasswordResetPage.installInstance();
        MyPlaceholderTestPage.installInstance();
        MyProjectDataMenuPage.installInstance();
        MyProjectManagePage.installInstance();
        MyProjectPage.installInstance();
        MyProxyPage.installInstance();
        MyRadioFieldTestPage.installInstance();
        MyRadioListTestPage.installInstance();
        MyRichTextEditorTestPage.installInstance();
        MyScriptTestPage.installInstance();
        MySharedState1TestPage.installInstance();
        MySharedState2TestPage.installInstance();
        MySlowTestPage.installInstance();
        MySmtpTestPage.installInstance();
        MySplitterTestPage.installInstance();
        MyStaticIncludeTestPage.installInstance();
        MyTabBookTestPage.installInstance();
        MyTenantManagePage.installInstance();
        MyTestMenuPage.installInstance();
        MyTextAreaLayoutTestPage.installInstance();
        MyTextFieldLayoutTestPage.installInstance();
        MyTimeAgoTestPage.installInstance();
        MyTimeoutPage.installInstance();
        MyToastTestPage.installInstance();
        MyUserActivationPage.installInstance();
        MyUserManagePage.installInstance();
        MyWyattTestPage.installInstance();

        add(MyAbsoluteLayoutTestPage.getInstance());
        add(MyAccordionTestPage.getInstance());
        add(MyAddressFieldTestPage.getInstance());
        add(MyAdminMenuPage.getInstance());
        add(MyAjaxCalendarTestPage.getInstance());
        add(MyAnimationTestPage.getInstance());
        add(MyAuditLogReportPage.getInstance());
        add(MyAutoCompleteTestPage.getInstance());
        add(MyBarcodeFieldTestPage.getInstance());
        add(MyBarcodeTestPage.getInstance());
        add(MyBlankTestPage.getInstance());
        add(MyBlockTestPage.getInstance());
        add(MyBorderLayoutTestPage.getInstance());
        add(MyBorderTestPage.getInstance());
        add(MyCardFlipTestPage.getInstance());
        add(MyCheckboxListTestPage.getInstance());
        add(MyChoiceFieldTestPage.getInstance());
        add(MyColorFieldTestPage.getInstance());
        add(MyCookieTestPage.getInstance());
        add(MyDashboardPage.getInstance());
        add(MyDateFieldTestPage.getInstance());
        add(MyDateIntervalFieldTestPage.getInstance());
        add(MyDetachedGroupTestPage.getInstance());
        add(MyDevApplicationLogsPage.getInstance());
        add(MyDevApplicationPropertiesPage.getInstance());
        add(MyDevBeanShellPage.getInstance());
        add(MyDevDataFixPage.getInstance());
        add(MyDevEmailsPage.getInstance());
        add(MyDevEnvironmentVariablesPage.getInstance());
        add(MyDevPerformanceLogDetailPage.getInstance());
        add(MyDevPerformanceLogSummaryPage.getInstance());
        add(MyDevSharedFileBrowserPage.getInstance());
        add(MyDevSqlPage.getInstance());
        add(MyDevSystemPropertiesPage.getInstance());
        add(MyDevUsersPage.getInstance());
        add(MyDevUtilityPage.getInstance());
        add(MyDialogTestPage.getInstance());
        add(MyDomainDropdownTestPage.getInstance());
        add(MyDownloadTestPage.getInstance());
        add(MyDragTestPage.getInstance());
        add(MyDropdownFieldTestPage.getInstance());
        add(MyDropzoneTestPage.getInstance());
        add(MyFacebookTestPage.getInstance());
        add(MyFieldTestPage.getInstance());
        add(MyFieldsetTestPage.getInstance());
        add(MyFilterTableRowTestPage.getInstance());
        add(MyFlexboxTestPage.getInstance());
        add(MyFormTestPage.getInstance());
        add(MyGmailTestPage.getInstance());
        add(MyGradientTestPage.getInstance());
        add(MyGridTestPage.getInstance());
        add(MyGroupTestPage.getInstance());
        add(MyHibernateCacheTestPage.getInstance());
        add(MyHiddenFieldTestPage.getInstance());
        add(MyHideErrorsTestPage.getInstance());
        add(MyHoverTestPage.getInstance());
        add(MyIntacctTestPage.getInstance());
        add(MyListCalendarTestPage.getInstance());
        add(MyListFieldTestPage.getInstance());
        add(MyLocalValueTestPage.getInstance());
        add(MyLoginPage.getInstance());
        add(MyLogoutPage.getInstance());
        add(MyMemoryLeakTestPage.getInstance());
        add(MyMultiTupleViewTestPage.getInstance());
        add(MyNavigation1TestPage.getInstance());
        add(MyNavigation2TestPage.getInstance());
        add(MyNotebookTestPage.getInstance());
        add(MyNvd3ChartTestPage.getInstance());
        add(MyOldValuesTestPage.getInstance());
        add(MyOpenWindowTestPage.getInstance());
        add(MyPasswordResetPage.getInstance());
        add(MyPlaceholderTestPage.getInstance());
        add(MyProjectDataMenuPage.getInstance());
        add(MyProjectManagePage.getInstance());
        add(MyProjectPage.getInstance());
        add(MyProxyPage.getInstance());
        add(MyRadioFieldTestPage.getInstance());
        add(MyRadioListTestPage.getInstance());
        add(MyRichTextEditorTestPage.getInstance());
        add(MyScriptTestPage.getInstance());
        add(MySharedState1TestPage.getInstance());
        add(MySharedState2TestPage.getInstance());
        add(MySlowTestPage.getInstance());
        add(MySmtpTestPage.getInstance());
        add(MySplitterTestPage.getInstance());
        add(MyStaticIncludeTestPage.getInstance());
        add(MyTabBookTestPage.getInstance());
        add(MyTenantManagePage.getInstance());
        add(MyTestMenuPage.getInstance());
        add(MyTextAreaLayoutTestPage.getInstance());
        add(MyTextFieldLayoutTestPage.getInstance());
        add(MyTimeAgoTestPage.getInstance());
        add(MyTimeoutPage.getInstance());
        add(MyToastTestPage.getInstance());
        add(MyUserActivationPage.getInstance());
        add(MyUserManagePage.getInstance());
        add(MyWyattTestPage.getInstance());
    }
}
